name: Black Formatting
on: [pull_request]
jobs:
  black:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.PAT_TOKEN }}  # Use a PAT with repo scope

      - name: Black Code Formatter
        uses: psf/black@stable
        with:
          options: "--verbose"
          src: "."
      
      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: 'Style fixes by Black'